apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guidellm-results
  namespace: mobis-poc
  labels:
    app: guidellm-benchmark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: lvms-vg-master
