apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: smollm2-135m-guardrails
  namespace: rhoai-poc
spec:
  replicas: 1
  autoConfig:
    inferenceServiceToGuardrail: smollm2-135m
  enableBuiltInDetectors: true
  enableGuardrailsGateway: true
  env:
    - name: OPENAI_BASE_URL
      value: http://smollm2-135m-metrics.rhoai-poc.svc.cluster.local:8080/v1
  otelExporter:
    otlpProtocol: grpc
