apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  finalizers:
  - lvmcluster.topolvm.io
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - default: true
      deviceSelector:
        paths:
        - /dev/disk/by-id/wwn-0x600062b21ad97480304424aac902dfaf
        - /dev/disk/by-id/wwn-0x600062b2197eedc0304424cdfd04bd64
      fstype: xfs
      name: vg-master
      nodeSelector:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - master01.poc.mobis.com
      thinPoolConfig:
        chunkSizeCalculationPolicy: Static
        metadataSizeCalculationPolicy: Host
        name: thin-pool
        overprovisionRatio: 10
        sizePercent: 90
    - deviceSelector:
        paths:
        - /dev/disk/by-id/wwn-0x6ec2a7203aa993002afe4f1a53386568
      fstype: xfs
      name: vg-worker
      nodeSelector:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker01.poc.mobis.com
      thinPoolConfig:
        chunkSizeCalculationPolicy: Static
        metadataSizeCalculationPolicy: Host
        name: thin-pool
        overprovisionRatio: 10
        sizePercent: 90
