apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: vg-master
        default: true
        fstype: xfs
        deviceSelector:
          paths:
            - /dev/disk/by-id/wwn-0x600062b21ad97480304424aac902dfaf
            - /dev/disk/by-id/wwn-0x600062b2197eedc0304424cdfd04bd64
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - master01.poc.mobis.com
        thinPoolConfig:
          name: thin-pool
          sizePercent: 90
          overprovisionRatio: 10
          chunkSizeCalculationPolicy: Static
          metadataSizeCalculationPolicy: Host
      - name: vg-worker
        fstype: xfs
        deviceSelector:
          paths:
            - /dev/disk/by-id/wwn-0x6ec2a7203aa993002afe4f1a53386568
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - worker01.poc.mobis.com
        thinPoolConfig:
          name: thin-pool
          sizePercent: 90
          overprovisionRatio: 10
          chunkSizeCalculationPolicy: Static
          metadataSizeCalculationPolicy: Host
