apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mobis-poc

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - cronjob.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: trans-job-fixer-script
    files:
      - fix-trans-jobs.sh
