apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trans-job-fixer
  namespace: customer-poc
  labels:
    app: trans-job-fixer
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "delete", "create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
