apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhoai-poc-staging

resources:
  - ../../llm-cpu
  - ../../monitoring
  - ../../network
  - ../../autoscaling
  - ../../guardrails
  - ../../rate-limit
  - ../../maas-routing
  - ../../multitenant
  - ../../mlops-loop

commonLabels:
  env: staging
  poc: rhoai
