apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    modelFormat: vLLM
    modelregistry.opendatahub.io/model-registry: mobis-registry
    modelregistry.opendatahub.io/model-version-name: v1
    modelregistry.opendatahub.io/registered-model-name: smollm2-135m
    pipeline.tekton.dev/last-deploy: '2026-05-21T08:17:30Z'
    pipeline.tekton.dev/s3-path: smollm2-135m/v2
    serving.kserve.io/autoscalerClass: external
    serving.kserve.io/deploymentMode: Standard
  finalizers:
  - inferenceservice.finalizers
  - odh.inferenceservice.finalizers
  labels:
    modelregistry.opendatahub.io/model-version-id: '11'
    modelregistry.opendatahub.io/registered-model-id: '10'
    opendatahub.io/dashboard: 'true'
  name: smollm2-135m
  namespace: mobis-poc
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 3
    minReplicas: 1
    model:
      args:
      - --dtype=float16
      - --max-model-len=2048
      - --enable-log-requests
      - --enable-log-outputs
      env:
      - name: VLLM_CONFIGURE_LOGGING
        value: '1'
      - name: HF_HUB_OFFLINE
        value: '1'
      - name: VLLM_LOGGING_LEVEL
        value: DEBUG
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '4'
          memory: 8Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '2'
          memory: 4Gi
          nvidia.com/gpu: '1'
      runtime: vllm-cuda-runtime
      storage:
        key: poc-s3-connection
        path: smollm2-135m/v2
