apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 50-masters-chrony-configuration
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,IyBBaXItZ2FwcGVkOiBubyBleHRlcm5hbCBOVFAgc2VydmVycyByZWFjaGFibGUKIyBNYXN0ZXIgc2VydmVzIGFzIGxvY2FsIE5UUCBzb3VyY2UgZm9yIGNsdXN0ZXIKc2VydmVyIDEwLjI0MC4yNTIuMSBpYnVyc3QgcHJlZmVyCmxvY2FsIHN0cmF0dW0gMTAKYWxsb3cgMTAuMjQwLjI1Mi4wLzI0CmRyaWZ0ZmlsZSAvdmFyL2xpYi9jaHJvbnkvZHJpZnQKbWFrZXN0ZXAgMS4wIDMKcnRjc3luYwpsb2dkaXIgL3Zhci9sb2cvY2hyb255Cg==
        mode: 420
        overwrite: true
        path: /etc/chrony.conf
