apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: poc-alert-routing
  namespace: rhoai-poc
spec:
  receivers:
  - emailConfigs:
    - from: ocp-alert@example.com
      requireTLS: false
      smarthost: mailhog.rhoai-poc.svc.cluster.local:1025
      to: poc-admin@example.com
    name: mailhog-webhook
  route:
    groupBy:
    - alertname
    groupInterval: 5m
    groupWait: 30s
    receiver: mailhog-webhook
    repeatInterval: 1h
