apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: poc-alert-routing
  namespace: rhoai-poc
spec:
  receivers:
  - emailConfigs:
    - from: rhoai@customer.com
      requireTLS: false
      smarthost: 10.240.13.184:25
      to: dt007000@customerdev-partners.com
    name: smtp-email
  route:
    groupBy:
    - alertname
    groupInterval: 5m
    groupWait: 30s
    receiver: smtp-email
    repeatInterval: 1h
