apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smollm2-135m-metrics
  namespace: rhoai-poc
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    targetPort: 8080
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: smollm2-135m
